services:
  postgres:
    image: postgres:16-alpine
    container_name: berrycrm-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: berrycrm
    ports:
      - "5432:5432"
    volumes:
      - berrycrm_postgres_data:/var/lib/postgresql/data

volumes:
  berrycrm_postgres_data:
